

<div style="page-break-before: always;" />

## 英文参考步骤（使用时英文方法需根据实际前处理进行调整）

### 固体样本提取 (Metabolites Extraction of Solid Sample)

Weight 25 mg sample to 1.5 mL Eppendorf tube. 100 μL water was added into sample and two 3.2 mm beads were added to the mixture. Samples were homogenized at 40 Hz for 4 min, and were sonicated in ice-water bath for 5 min. 400 μL extraction agent (1% acetic acid in ACN, containing internal standards) was added into sample. Samples were homogenized at 40 Hz for 4 min, and were sonicated in ice-water bath for 5 min. After that, samples were incubated at room temperature for 1 h. Then 600 μL extractant (Ethyl Acetate:n-Hexane, 2:1 (v/v)) was added into sample and he mixed samples were oscillated for 5 min. After centrifugation (5 min, 6000 rpm), the supernatant was evaporated to dryness under a gentle stream of nitrogen for 30 min and was reconstituted in 50 μL of solution (MeOH:H2O, 4:1 (v/v)). After centrifugation (15 min, 12000 rpm), the clear supernatant was subjected to UHPLC-MS/MS analysis. `r if(l.a$has_qc){'Pool equal amount of each sample as QC sample.'}`


### 液体样本提取 (Metabolites Extraction of Liquid Sample)

The samples were thawed in ice water bath and was vortexed for 30s. 100 μL of liquid samples was mixed with 400 µL extraction agent (1% acetic acid in ACN, containing internal standards) and were vortexed for 30 s. Two 3.2 mm beads were added to the mixture, and then Samples were homogenized at 40 Hz for 4 min, and were sonicated in ice-water bath for 5 min. The homogenization and sonication repeated 2 times. Then 600 μL extractant (Ethyl Acetate:n-Hexane, 2:1 (v/v)) was added into sample and he mixed samples were oscillated for 5 min. After centrifugation (5 min, 6000 rpm), the supernatant was evaporated to dryness under a gentle stream of nitrogen for 30 min and was reconstituted in 50 μL of solution (MeOH:H2O, 4:1 (v/v)). After centrifugation (15 min, 12000 rpm), the clear supernatant was subjected to UHPLC-MS/MS analysis. `r if(l.a$has_qc){'Pool equal amount of each sample as QC sample.'}`



### 标准曲线 (Standard Solution Preparation)

Different volume of each standard stock solution was transferred to a flask to form a mixed working standard solution. A series of calibration standard solutions were then prepared by stepwise dilution of this mixed standard solution (containing isotopically-labelled internal standard mixture in identical concentrations with the samples). 

### 仪器条件 (Instrument Parameter)

The LC separation was carried out using an UPLC System (Agilent 1290 UPLC), equipped with a Phenomen Kinetex C18 (2.1 * 100 mm, 2.6 μm). The mobile phase A was 0.1% FA in H2O, and the mobile phase B was mixed H2O and MeOH (5:95) containing 10 mmol/L ammonium formate. The auto-sampler temperature was set at 6℃ and the injection volume was 2 μL. AB Sciex Triple Quad 7500+ mass spectrometer was applied for assay development. Typical ion source parameters were as follows: IonSpray Voltage: +3000V/-2500V, Curtain Gas: 40 psi, Temperature: 400 ℃, Ion Source Gas 1: 70 psi, Ion Source Gas 2: 70psi.

Raw data files generated by LC-MS/MS were processed with SCIEX OS Work Station Software (3.4.5.828), compounds quantification was analyzed with automation analysis software BIOTREE BioBud (v2.0.4).


# 参考文献 {-}

[1]​ 中华人民共和国农业部. 中华人民共和国国家标准: 农业部783号公告-2-2006[J].

[2]​ 中华人民共和国农业农村部，中华人民共和国国家卫生健康委员会，国家市场监督管理总局. 中华人民共和国国家标准: GB 31656.19-2025[J].

[3]​ 中华人民共和国国家卫生和计划生育委员会. 中华人民共和国国家标准: GB 5009.253-2016[S].

[4]​ 中华人民共和国农业部. 中华人民共和国国家标准: 农业部1031号公告-2-2008[S].

[5]​ 中华人民共和国农业农村部，中华人民共和国国家卫生健康委员会，国家市场监督管理总局. 中华人民共和国国家标准: GB 31656.8-2021[J]. 

[6] 国家认证认可监督管理委员会. 中华人民共和国出入境检验检疫行业标准: SN/T 4606-2016[S]. 北京：中国标准出版社, 2018.

[7]​ Lei You ,  Jing Kou ,  Mengdie Wang ,  Guoqin Ji ,  Xiang Li et al. An exposome atlas of serum reveals the risk of chronic diseases in the Chinese population [J]. Nature Communications, 2024, 15: 2268.