

<div style="page-break-before: always;" />

## 英文参考步骤（使用时英文方法需根据实际前处理进行调整）

### 固体样本提取 (Metabolites Extraction of Solid Sample)

Weight 25 mg sample to 2 mL EP tube. 700 μL extraction agent (MeOH:H2O=4:1, containing internal standards) was added into sample and two 3.2 mm beads were added to the mixture. Samples were homogenized at 40 Hz for 4 min, and were sonicated in ice-water bath for 5 min. The homogenization and sonication cycle was repeated for 3 times. After that, samples were incubated at -40 ℃ for 1 h. Then all the samples were centrifuged at 12000 rpm and 4 ℃ for 15 min. Transfer supernatant of each sample to glass vial for LC-MS/MS analysis. `r if(l.a$has_qc){'Pool equal amount of each sample as QC sample.'}`


### 液体样本提取 (Metabolites Extraction of Liquid Sample)

The samples were thawed in ice water bath and was vortexed for 30s. 100 μL of liquid samples was mixed with 400 µL methanol containing internal standard and were vortexed for 30 s. After sonication in ice-water bath for 15 min, samples were incubated at -40 ℃ for 1 h. Then the samples were centrifuged at 12000 rpm and 4 ℃ for 15 min, 200 μL supernatant of each sample was transferred to glass vial for LC-MS/MS analysis. `r if(l.a$has_qc){'Pool equal amount of each sample as QC sample.'}`



### 标准曲线 (Standard Solution Preparation)

Different volume of each standard stock solution was transferred to a flask to form a mixed working standard solution. A series of calibration standard solutions were then prepared by stepwise dilution of this mixed standard solution (containing isotopically-labelled internal standard mixture in identical concentrations with the samples). 

### 仪器条件 (Instrument Parameter)

For RP system, The LC separation was carried out using an UPLC System (Agilent 1290 UPLC), equipped with a ACQUITY UPLC BEH C18 Column (1.7 µm, 2.1 mm × 150 mm). The mobile phase A was 0.1% FA in H2O, and the mobile phase B was mixed H2O and MeOH (5:95) containing 10 mmol/L ammonium formate. For HILIC system, The LC separation was carried out using an UPLC System (Agilent 1290 UPLC), equipped with a Atlantis Premier BEH Z-HILIC Column (1.7 µm，2.1 mm × 150 mm). The mobile phase A was 10% ACN in H2O containing 10 mmol/L ammonium acetate, and the mobile phase B was mixed H2O and ACN (10:90) containing 10 mmol/L ammonium acetate. The auto-sampler temperature was set at 6 ℃ and the injection volume was 1 μL. AB Sciex Triple Quad 6500+ mass spectrometer was applied for assay development. Typical ion source parameters were as follows: IonSpray Voltage: +5000V/-4500V, Curtain Gas: 35 psi, Temperature: 400 ℃, Ion Source Gas 1: 50 psi, Ion Source Gas 2: 50psi.

Raw data files generated by LC-MS/MS were processed with SCIEX Analyst Work Station Software (1.7.3), metabolites quantification was analyzed with automation analysis software BIOTREE BioBud (v2.0.4).


# 参考文献 {-}

1. Hosseinkhani, F., Dubbelman, A. C., Karu, N., Harms, A. C., & Hankemeier, T. (2021). Towards Standards for Human Fecal Sample Preparation in Targeted and Untargeted LC-HRMS Studies. Metabolites, 11(6), 364.

2. Anesi, A., Berding, K., Clarke, G., Stanton, C., Cryan, J. F., Caplice, N., Ross, R. P., Doolan, A., Vrhovsek, U., & Mattivi, F. (2022). Metabolomic Workflow for the Accurate and High-Throughput Exploration of the Pathways of Tryptophan, Tyrosine, Phenylalanine, and Branched-Chain Amino Acids in Human Biofluids. Journal of proteome research, 21(5), 1262–1275. 

3. Li, L., Wang, T., Ning, Z., Zhang, X., Butcher, J., Serrana, J. M., Simopoulos, C. M. A., Mayne, J., Stintzi, A., Mack, D. R., Liu, Y. Y., & Figeys, D. (2023). Revealing proteome-level functional redundancy in the human gut microbiome using ultra-deep metaproteomics. Nature communications, 14(1), 3428. 

4. Yuan, M., Breitkopf, S. B., Yang, X., & Asara, J. M. (2012). A positive/negative ion-switching, targeted mass spectrometry-based metabolomics platform for bodily fluids, cells, and fresh and fixed tissue. Nature protocols, 7(5), 872–881.

5. Wernisch, S., & Pennathur, S. (2016). Evaluation of coverage, retention patterns, and selectivity of seven liquid chromatographic methods for metabolomics. Analytical and bioanalytical chemistry, 408(22), 6079–6091.