## 实验小结

```{r echo=FALSE,warning=FALSE}
library(pander)
data_group <- read.xlsx(paste0(l.a$inDir,"/", grep('headMessage', list.files(l.a$inDir), value = T)), sheet = '样本分组')
if(sum(colnames(data_group) == '组别') > 1) {
  sum_spl2 <- sum(data_group[,colnames(data_group) == '实验检测'], na.rm = T)
} else {
  sum_spl2 <- sum(as.numeric(unlist(data_group[data_group$组别 == '实验检测', -1])), na.rm = T)
} 
str <- paste0("本项目采用UHPLC-MRM-MS/MS的方法，采用内标法，针对样品中的Alanine、Aspartate、Gamma-Aminobutyric acid、Glutamate、Glutamine、Glycine、Methionine、Proline、Serine、Glutathione、Oxidized glutathione、Thiamine pyrophosphate、β-Nicotinamide adenine dinucleotide phosphate等146种目标代谢物，共计完成", sum_spl2, "例", l.a$spl_type, "样本的分析检测。")
pander(str)
```

## 英文参考步骤（使用时英文方法需根据实际前处理进行调整）

### 固体样本提取 (Metabolites Extraction of Solid Sample)

Weight 25 mg sample to 2 mL EP tube. 500 μL extraction agent (MeOH:H2O=3:1, containing internal standards) was added into sample and two 3.2 mm beads were added to the mixture. Samples were homogenized at 40 Hz for 4 min, and were sonicated in ice-water bath for 5 min. The homogenization and sonication cycle was repeated for 3 times. After that, samples were incubated at -40 ℃ for 1 h. Then all the samples were centrifuged at 12000 rpm and 4 ℃ for 15 min. 400 μL of supernatant was transferred to a 2.0 mL Eppendorf tube and dried under vacuum. The residue was reconstituted in 200 μL of methanol: acetonitrile: water (1: 1: 2, v/v/v), filtered, and the liquid was transferred to an autosampler vial for analysis.

### 液体样本提取 (Metabolites Extraction of Liquid Sample)

The samples were thawed in ice water bath and was vortexed for 30s. 100 μL of liquid samples was mixed with 300 µL methanol containing internal standard and were vortexed for 30 s. After sonication in ice-water bath for 15 min, samples were incubated at -40 ℃ for 1 h. Then the samples were centrifuged at 12000 rpm and 4 ℃ for 15 min, 200 μL supernatant was transferred to a 2.0 mL Eppendorf tube and dried under vacuum. The residue was reconstituted in 160 μL of methanol: acetonitrile: water (1: 1: 2, v/v/v), filtered, and the liquid was transferred to an autosampler vial for analysis.

### 仪器条件 (Instrument Parameter)

For RP system, The LC separation was carried out using an UPLC System (Agilent 1290 UPLC), equipped with a ACQUITY UPLC BEH C18 Column（1.7 µm, 2.1 mm ×150 mm). The mobile phase A was 0.1% FA in H2O, and the mobile phase B was mixed H2O and MeOH (5:95) containing 10 mmol/L ammonium formate. For HILIC system, The LC separation was carried out using an UPLC System (Agilent 1290 UPLC), equipped with a Atlantis Premier BEH Z-HILIC Column（1.7 µm，2.1 mm ×150 mm）. The mobile phase A was 10% ACN in H2O containing 10 mmol/L ammonium acetate, and the mobile phase B was mixed H2O and ACN (10:90) containing 10 mmol/L ammonium acetate. The auto-sampler temperature was set at 6 ℃ and the injection volume was 1 μL. AB Sciex Triple Quad 6500+ mass spectrometer was applied for assay development. Typical ion source parameters were as follows: IonSpray Voltage: +5000V/-4500V, Curtain Gas: 35 psi, Temperature: 400 ℃, Ion Source Gas 1: 50 psi, Ion Source Gas 2: 50psi.

Raw data files generated by LC-MS/MS were processed with SCIEX Analyst Work Station Software (1.7.3), metabolites quantification was analyzed with automation analysis software BIOTREE Bio Bud (v2.0.3) .


### 标准曲线 (Standard Solution Preparation)

Different volume of each standard stock solution was transferred to a flask to form a mixed working standard solution. A series of calibration standard solutions were then prepared by stepwise dilution of this mixed standard solution (containing isotopically-labelled internal standard mixture in identical concentrations with the samples).

### 方法检出限及定量限（LOD and LOQ）

The calibration standard solution was diluted stepwise, with a dilution factor of 2.These standard solutions were subjected to UHPLC-MRM-MS analysis. The signal-to-noise ratios (S/N) were used to determine the lower limits of detection  (LODs) and lower limits of quantitation (LOQs). The LODs and LOQs were defined as the analyte concentrations that led to peaks with signal-to-noise ratios (S/N) of 3 and 10, respectively, according to the US FDA guideline for bioanalytical method validation.
 
### 方法精密度及准确度（Precision and Accuracy）

The precision of the quantitation was measured as the relative standard deviation (RSD), determined by injecting analytical replicates of a QC sample. The accuracy of quantitation was calculated as \[(mean observed concentration) / (Theoretical concentration)] × 100%.

### 色谱分离（LC Separation）

Figure 2-5 shows the extracted ion chromatographs (EICs) from a standard solution and a sample of the targeted analytes under the optimal conditions. From these figures,  (i) all of the analytes showed symmetrical peak shapes,  (ii) baseline separations were obtained, (iii) and the retention time and peak shapes for all of the analytes showed good correlation between the standard solution and the real sample.

### 方法定量参数（Analysis Metrics）

Table S3 lists the resulting lower-limits of detection and quantitation  (LODs and LOQs), and the LODs ranged from `r paste0(ifelse(min(data_S3$rawy)<1, signif(min(data_S3$rawy),2),round(min(data_S3$rawy),2)), 'to', ifelse(max(data_S3$rawy)<1, signif(max(data_S3$rawy),2),round(max(data_S3$rawy),2)), ' ',l.a$unit_CC)`, the LOQs ranged from `r paste0(ifelse(min(data_S3$xmin)<1, signif(min(data_S3$xmin),2),round(min(data_S3$xmin),2)), 'to', ifelse(max(data_S3$xmin)<1, signif(max(data_S3$xmin),2),round(max(data_S3$xmin),2)), ' ',l.a$unit_CC)` for all the analytes. Correlation coefficients (R2) of regression fitting were above `r round(min(data_S3$score),3)` for all the analytes, indicating a good quantitative relationship between the MS responses and the analyte concentrations, which was satisfying for targeted metabolomics analysis (see Figure S1-Calibration).
Table S4 lists the analytical recoveries and relative standard deviations of the QC samples, with 3 technical replicates. The recoveries determined were `r min(data_S4$Accuracy)`% -`r max(data_S4$Accuracy)`% for all the analytes, with all the RSDs below `r max(data_S4$RSD)`% (n = 3).
The analysis metrics indicated that the method allowed accurate quantitation of the targeted metabolites in the biological sample, in the concentration range described as above.

### 样本中目标代谢物检测结果（Quantification Results）

*Solid*
C~C~ (nmol/L) is Calculated Concentration, that is calculated by calibration curve. C~M~ (Metabolite Concentration, nmol/g) is the content of target metabolites in the sample. It equal to Calculated Concentration C~C~ (nmol/L) multiplied by Extration Volumn (µL), divided by sample mass m (mg), divided by 1,000.

*Liquid*
C~C~ (nmol/L) is Calculated Concentration, that is calculated by calibration curve. C~M~ (Metabolite Concentration, nmol/L) is the content of target metabolites in the sample. It equal to Calculated Concentration C~C~ (nmol/L) multiplied by Extration Volumn (µL), divided by VS（Sample Volume, µL), divided by Concentration Factor(CF).

<div style="page-break-before: always;" />

## 参考文献

1. Hosseinkhani, F., Dubbelman, A. C., Karu, N., Harms, A. C., & Hankemeier, T. (2021). Towards Standards for Human Fecal Sample Preparation in Targeted and Untargeted LC-HRMS Studies. Metabolites, 11(6), 364.

2. Anesi, A., Berding, K., Clarke, G., Stanton, C., Cryan, J. F., Caplice, N., Ross, R. P., Doolan, A., Vrhovsek, U., & Mattivi, F. (2022). Metabolomic Workflow for the Accurate and High-Throughput Exploration of the Pathways of Tryptophan, Tyrosine, Phenylalanine, and Branched-Chain Amino Acids in Human Biofluids. Journal of proteome research, 21(5), 1262–1275. 

3. Li, L., Wang, T., Ning, Z., Zhang, X., Butcher, J., Serrana, J. M., Simopoulos, C. M. A., Mayne, J., Stintzi, A., Mack, D. R., Liu, Y. Y., & Figeys, D. (2023). Revealing proteome-level functional redundancy in the human gut microbiome using ultra-deep metaproteomics. Nature communications, 14(1), 3428. 

4. Yuan, M., Breitkopf, S. B., Yang, X., & Asara, J. M. (2012). A positive/negative ion-switching, targeted mass spectrometry-based metabolomics platform for bodily fluids, cells, and fresh and fixed tissue. Nature protocols, 7(5), 872–881.
