

## 英文参考步骤(请根据项目实际情况进行修改)

***Metabolites Extraction of Solid Sample***

LC-MS/MS: Weight 25 mg sample to 2 mL EP tube. 700 μL extraction agent (MeOH:H2O=4:1, containing internal standards) was added into sample and two 5 mm beads were added to the mixture. Samples were homogenized at 40 Hz for 4 min, and were sonicated in ice-water bath for 5 min. The homogenization and sonication cycle was repeated for 3 times. After that, samples were incubated at -40 ℃ for 1 h. Then all the samples were centrifuged at 12000 rpm and 4 ℃ for 15 min. Transfer supernatant of each sample to glass vial for LC-MS/MS/MS analysis. `r if(l.a$has_qc){'Pool equal amount of each sample as QC sample.'}`[@fecal-sample]

GC-MS: Weight 25 mg sample into the 2 mL EP tubes. 1 mL H2O was added, and the mixture was vortexed for 10 s. The sample was homogenized in ball mill for 4 min at 40 Hz, and then was sonicated for 5 min in ice water，repeat 3 times. Centrifuge for 20 min at 5000 rpm, 4 ℃. Transfer 0.8 mL supernatant into a fresh 2 mL EP tubes; Add 0.1 mL 50 % H2SO4 and 0.8 mL of extracting solution ( methyl tert-butyl ether) containing internal standard. The mixture was vortexed for 10 s, and was oscillated in 10 min, then ultrasound treated for 10 min (incubated in ice water). Centrifuge for 15 min at 10000 rpm, 4 ℃. Keep at −20 ℃ for 30 min. Transfer the supernatant into a 2 mL glass vial for GC-MS analysis.

***Metabolites Extraction of Liquid Sample***

LC-MS/MS: The samples were thawed in ice water bath and was vortexed for 30s. 100 μL of liquid samples was mixed with 400 µL methanol containing internal standard and were vortexed for 30 s. After sonication in ice-water bath for 15 min, samples were incubated at -40 ℃ for 1 h. Then the samples were centrifuged at 12000 rpm and 4 ℃ for 15 min, 200 μL supernatant of each sample was transferred to glass vial for LC-MS/MS/MS analysis. `r if(l.a$has_qc){'Pool equal amount of each sample as QC sample.'}`[@urine-sample]

GC-MS: Take 100 µL sample into the 2 mL EP tubes. 50 µL 50% H2SO4 and 200 µL extracting agent (MTBE) were added to samples. The mixture was vortexed for 10 s. The sample was oscillated for 10 min, then ultrasound treated for 10 min (incubated in ice water). Centrifuge for 15 min at 10000 rpm at 4 ℃. Keep at −20 ℃ for 30 min. Transfer the supernatant into a 2 mL glass vial for GC-MS analysis.

***标准曲线（Standard Solution Preparation）***

Different volume of each standard stock solution was transferred to a flask to form a mixed working standard solution. A series of calibration standard solutions were then prepared by stepwise dilution of this mixed standard solution (containing isotopically-labelled internal standard mixture in identical concentrations with the samples).

***仪器条件（LC-MS/MS & GC-MS Analysis）***

LC-MS/MS: The LC separation was carried out using an UPLC System (Agilent 1290 UPLC), equipped with a ACQUITY UPLC BEH C18 Column (1.7 µm, 2.1 mm * 150 mm). The mobile phase A was 0.1% FA in H2O, and the mobile phase B was mixed H2O and MeOH (5:95) containing 10 mmol/L ammonium acetate. The auto-sampler temperature was set at 6 ℃ and the injection volume was 1 μL. AB Sciex QTrap 6500 plus mass spectrometer was applied for assay development. Typical ion source parameters were as follows: IonSpray Voltage: +5000V/-4500V, Curtain Gas: 35 psi, Temperature: 450 ℃, Ion Source Gas 1: 50 psi, Ion Source Gas 2: 50psi.

Raw data files generated by LC-MS/MS were processed with SCIEX Analyst Work Station Software (1.7.3), metabolites quantification was analyzed with automation analysis software BIOTREE BioBud (v2.0.4).

GC-MS: The GC-MS was performed on Agilent GC7890B-5977B gas chromatography-mass spectrometer. The system utilized a HP-FFAP capillary column. A 1 μL aliquot of the analyte was injected in split mode (5:1). Helium was used as the carrier gas, the front inlet purge flow was 3 mL min−1, and the gas flow rate through the column was 1.2 mL min−1. The initial temperature was kept at 50 ℃ for 1 min, then raised to 150 ℃ at a rate of 50 ℃ min−1 for 1 min, then raised to 170 ℃ at a rate of 10 ℃ min−1 ,then raised to 225 ℃ at a rate of 25 ℃ min−1 for 1 min,then raised to 240 ℃ at a rate of 40 ℃ min−1 for 1 min. The injection,. The injection, The injection, transfer line, quad and ion source temperatures were 240 ℃, 240 ℃, 150 ℃ and 240 ℃. The mass spectrometry data were acquired in SIM mode.

Raw data files generated by GC-MS were processed with Agilent MassHunter Workstation(10.2), metabolites quantification was analyzed with automation analysis software BIOTREE BioBud (v2.0.4).








