
### 上机检测

***1、流动相条件：***

本项目使用Agilent 1290 Infinity II超高效液相色谱仪，通过ACQUITY UPLC BEH C18 Column（1.7 µm, 2.1 mm ×150 mm）液相色谱柱对目标化合物进行色谱分离。液相色谱A相为5mM乙酸铵，B相为乙腈。柱温箱温度为45 °C，样品盘设为4 °C，进样体积为2 μL。

***2、质谱条件：***

本项目使用6500 QTRAP+三重四极杆质谱仪，匹配ESI电喷雾离子源，以多反应监测(MRM)模式进行质谱 分析。离子源参数如下：Ion Spray Voltage =±4500 V, Ion Source Gas 1=50 psi, Ion Source Gas 2=50 psi, Temperature (+/-)=450°C/400°C,Curtain Gas (+/-)=40/35 psi 。

进行UHPLC-MS/MS分析之前，将目标化合物标准溶液引入质谱中。针对每个目标化合物，选取信号强度 最高的数个母离子-子离子对(Transition)，对其MRM参数进行优化，并选取其中响应最好的离子对用于定量分析，其它离子对用于目标化合物定性分析，具体参数见Table S2。

本项目中，所有数据采集工作均通过Analyst（1.7.3，SCIEX）和 Biotree Biobud (v2.0.3)来完成。


### 校准曲线

采用前文所描述的方法对校准溶液进行UHPLC-MRM-MS分析。校准曲线如Figure S1-Calibration所示，y表示目标化合物和对应内标物的峰面积之比，x表示目标化合物的浓度(nmol/L)。若某一校准浓度Accuracy超出80-120%范围，则将该浓度校准点排除。

<div style="page-break-before: always;" />
### 方法检出限及定量限

将校准溶液依次稀释2倍后进行UHPLC-MRM-MS分析，通过其信噪比来计算方法的检出限和定量限。方法 最低检出限(LLOD)定义为信噪比为3时所对应的化合物浓度，方法最低定量限(LLOQ)定义为信噪比为10时所 对应的化合物浓度(US FDA guideline for bioanalytical method validation)。

### 方法精密度及准确度

方法的精密度通过QC样品重复进样的标准相对偏差(RSD)来评估。准确度通过测得浓度与理论浓度的百分比值来评估。
