
## 实验小结

本项目采用UHPLC-MRM-MS/MS的方法，采用内标法，针对样品中的 Ethanolamine、Glycine、D-Alanine、β-Alanine、L-Alanine、2-Aminoisobutyric acid、L-2-Aminobutyric acid、(S)-beta-Aminoisobutyric acid、γ-Aminobutyric acid、L-Serine、D-Serine、L-Proline、D-Proline、5-Aminovaleric acid、L-Valine、D-Valine、D-Threonine、L-Threonine、L-Homoserine、Taurine、L-Pipecolic acid、trans-L-Hydroxyproline、D-Isoleucine、L-Isoleucine、L-Leucine、D-leucine、D-Asparagine、L-Asparagine、D-Aspartic acid、L-Aspartic acid、4-Aminobenzoic acid、D-Glutamine、L-Glutamine、D-Glutamic acid、L-Glutamic acid、L-Methionine、D-Methionine、L-Histidine、D-Histidine、L-2-Aminoadipic acid、L-Phenylalanine、D-Phenylalanine、L-Cysteic acid、3-Methyl-histidine、1-Methyl-L-histidine、D-Arginine、L-Arginine、D-Citrulline、L-Citrulline、D-Tyrosine、L-Tyrosine、L-Homoarginine、L-Homocitrulline、Symmetric dimethylarginine、D-Tryptophan、L-Tryptophan、L-Kynurenine、L-Carnosine、L-Argininosuccinic acid、L-2,4-diaminobutyric acid、D-Cysteine、L-Cysteine、L-Ornithine、D-Ornithine、D-Lysine、L-Lysine、L-Cystine、D-Cystine、L-γ-glutamyl-L-cysteine、L-Homocystine、Glutathione等71种氨基酸目标代谢物，共计完成`r sum(data_group[2, -1])`例`r gsub("样本.*", "", headMessage["项目名称", 1])`样本的分析检测。


## 英文参考步骤

### 固体样本处理步骤（Metabolites Extraction）

Solid samples were placed on dry ice and kept frozen while being prepared. Weigh 25 mg of the sample into a 2.0 mL Eppendorf tube at low temperature. A 1000 μL aliquot of extract solvent  (80% MeOH, containing  internal  standards)  and 2 steel beads of 3.2 mm were added. Samples were homogenized at 40 Hz for 4 min, and were sonicated in ice-water bath for 5 min. The homogenization and sonication cycle was repeated for 3 times. After that, samples were incubated at -40 ℃ for 1 h. Then all the samples were centrifuged at 12000 rpm and 4 ℃ for 15 min. 100 μL of supernatant was transferred to a 2.0 mL Eppendorf tube. 100 μL of derivatization reagent and 50 μL of 1 M NaHCO3 were added to the sample. It was vortexed evenly and incubated in a 40℃ water bath for 1 hour. Then 18 μL of 10% FA was added to quench the reaction. The mixture was centrifuged at 12,000 rpm and 4°C for 5 minutes. The supernatant was transferred to an autosampler vial for analysis.

### 液体样本提取 (Metabolites Extraction of Liquid Sample)

The samples were thawed in ice water bath and was vortexed for 30s. 50 μL of liquid samples was mixed with 200 µL methanol containing internal standard and were vortexed for 30 s. After sonication in ice-water bath for 15 min, samples were incubated at -40 ℃ for 1 h. 100 μL of supernatant was transferred to a 2.0 mL Eppendorf tube. 100 μL of derivatization reagent and 50 μL of 1 M NaHCO3 were added to the sample. It was vortexed evenly and incubated in a 40℃ water bath for 1 hour. Then 18 μL of 10% FA was added to quench the reaction. The mixture was centrifuged at 12,000 rpm and 4°C for 5 minutes. The supernatant was transferred to an autosampler vial for analysis.

### 仪器条件 (Instrument Parameter)

The UHPLC separation was carried out using Agilent 1290 UPLC, equipped with a ACQUITY UPLC BEH C18 Column（1.7 µm, 2.1 mm *150 mm). The mobile phase A was 5 mM ammonium acetate in water, and the mobile phase B was acetonitrile. The column temperature was set at 45 oC. The auto-sampler temperature was set at 4 oC and the injection volume was 2 μL.

6500 QTRAP+ Mass Spectrometer  (SCIEX, USA), equipped with an electrospray ionization interface, was applied for assay development. Typical ion source parameters were: Ion Spray Voltage =±4500 V, Ion Source Gas 1=50 psi, Ion Source Gas 2=50 psi, Temperature  (+/- )=450 °C/400 °C,Curtain Gas (+/-)=40/35 psi.

The MRM parameters for each of the targeted analytes were optimized using flow injection analysis, by injecting the standard solutions of the individual analytes, into the ESI source of the mass spectrometer. Several most sensitive transitions were used in the MRM scan mode to optimize the collision energy for each Q1/Q3 pair  (Table S2). Among the optimized MRM transitions per analyte, the Q1/Q3 pairs that showed the highest sensitivity and selectivity were selected as ‘quantifier ’ for quantitative monitoring. The additional transitions acted as ‘qualifier ’ for the purpose of verifying the identity of the target analytes. Analyst  (1.7.3，SCIEX) and Biotree Biobud (v2.0.3) were employed for MRM data acquisition.

### 标准曲线 (Standard Solution Preparation)

Stock solutions were individually prepared by dissolving or diluting each standard substance to give a final concentration of 10 mmol/L. An aliquot of each of the stock solutions was transferred to a 5 mL flask to form a mixed working standard solution. A series of calibration standard solutions were then prepared by stepwise dilution of this mixed  standard  solution  (containing  isotopically-labelled  internal  standard  mixture  in identical concentrations with the samples).

Calibration  solutions were  subjected to UHPLC-MRM analysis using the methods described above. Figure S1-Calibration summarizes the results for the calibration curves where y i s the ratio of the peak area of the target compound to the corresponding internal standard, and x i s the concentration (ng/mL) for analyte. The level was excluded from the calibration if the accuracy of calibration was not within 80 -120%. Detailed calibration curves for individual analytes are shown in Figure S1-Calibration.

### 方法检出限及定量限（LOD and LOQ）

The calibration standard solution was diluted stepwise, with a dilution factor of 2.
These standard solutions were subjected to UHPLC-MRM-MS analysis. The signal-to-noise ratios (S/N) were used to determine the lower limits of detection  (LODs) and lower limits of quantitation (LOQs). The LODs and LOQs were defined as the analyte concentrations that led to peaks with signal-to-noise ratios (S/N) of 3 and 10, respectively, according to the US FDA guideline for bioanalytical method validation.

### 方法精密度及准确度（Precision and Accuracy）

The precision of the quantitation was measured as the relative standard deviation (RSD), determined by injecting analytical replicates of a QC sample. The accuracy of quantitation was calculated as [(mean observed concentration) / (Theoretical concentration)] × 100%.

### 色谱分离（LC Separation）

Figure 2 and Figure 3 shows the extracted ion chromatographs (EICs) from a standard solution and a sample of the targeted analytes under the optimal conditions. As can be seen from this figure,  (i) all of the analytes showed symmetrical peak shapes,  (ii) baseline separations were obtained, (iii) and the retention time and peak shapes for all of the analytes showed good correlation between the standard solution and the real sample.

### 方法定量参数（Analysis Metrics）

Table S3 lists the resulting lower-limits of detection and quantitation  (LODs and LOQs), and the LODs ranged from `r paste0(ifelse(min(data_S3$rawy)<1, min(data_S3$rawy),min(data_S3$rawy)), ' to ', ifelse(max(data_S3$rawy)<1, max(data_S3$rawy),max(data_S3$rawy)))` nmol/L, the LOQs ranged from `r paste0(ifelse(min(data_S3$xmin)<1, min(data_S3$xmin),min(data_S3$xmin)), ' to ', ifelse(max(data_S3$xmin)<1, max(data_S3$xmin),max(data_S3$xmin)))` nmol/L for all the analytes. Correlation coefficients (R2) of regression fitting were above `r min(data_S3$score)` for all the analytes, indicating a good quantitative relationship between the MS responses and the analyte concentrations, which was satisfying for targeted metabolomics analysis (see Figure S1-Calibration).

Table S4 lists the analytical recoveries and relative standard deviations of the QC samples, with 3 technical replicates. The recoveries determined were `r min(data_S4$Accuracy)`% -`r max(data_S4$Accuracy)`% for all the analytes, with all the RSDs below `r max(data_S4$RSD)`% (n = 3).

The analysis metrics indicated that the method allowed accurate quantitation of the targeted metabolites in the biological sample, in the concentration range described as above.

### 样本中目标代谢物检测结果（Quantification Results）

*Solid*

C~C~ (nmol/L) is Calculated Concentration, that is calculated by calibration curve. C~M~ (Metabolite Concentration, nmol/g) is the content of target metabolites in the sample. It equal to Calculated Concentration C~C~ (nmol/L) multiplied by Extration Volumn (µL), divided by sample mass m (mg), divided by 1,000.

*Liquid*

C~C~ (nmol/L) is Calculated Concentration, that is calculated by calibration curve. C~M~ (Metabolite Concentration, nmol/L) is the content of target metabolites in the sample. It equal to Calculated Concentration C~C~ (nmol/L) multiplied by Extration Volumn (µL), divided by VS（Sample Volume, mL).

# 参考文献

1.	Marfey, P. Determination ofD-amino acids. II. Use of a bifunctional reagent, 1,5-difluoro-2,4-dinitrobenzene. Carlsberg Res. Commun. 49, 591 (1984). 

2.	Xie, C., Chen, Y., Wang, X., Song, Y., Shen, Y., Diao, X., Zhu, L., Wang, J., & Cai, Z. (2022). Chiral derivatization-enabled discrimination and on-tissue detection of proteinogenic amino acids by ion mobility mass spectrometry. Chemical science, 13(47), 14114–14123.
